Repository lettucecfd/lettuce, pull requests merged in 2022-01, with the labels that each got.

#105 Move CI from Travis to Github Actions
  .github/workflows/CI.yml
  .github/workflows/lint.yml
  .gitignore
  .travis.yml
Labels: enhancement, fix

#99 Porous Media example
  examples/porous_medium.ipynb
Labels: duplicate

#98 versioneer update
  .codeclimate.yml
  lettuce/__init__.py
  lettuce/_version.py
  versioneer.py
Labels: fix

#95 add hdf5 reporter/writer and dataset for torch.util.dataloader
  .github/workflows/CI.yml
  README.rst
  lettuce/__init__.py
  lettuce/datautils.py
  requirements.txt
  tests/test_reporters.py
Labels: usability
